/**
 * The manifest is valid, it reuses the icons WP-0.08 already shipped, and it
 * says nothing commercial (Constitution §11.4, Rule 7).
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  PWA_BACKGROUND_COLOR,
  PWA_ICONS,
  PWA_THEME_COLOR,
  buildWebManifest,
  manifestProse,
} from '@/lib/pwa/manifest';
import { APPLE_ICON_SIZE } from '@/lib/og/brand';
import { SITE_DESCRIPTION } from '@/shared/config/site';
import { sweepMessage } from '@/lib/growth/commercialLanguage';
import { sweepForLoss } from '@/lib/growth/lossLanguage';

const ROOT = join(__dirname, '..', '..', '..');

describe('web app manifest', () => {
  const manifest = buildWebManifest();

  it('carries every field a browser needs to treat it as installable', () => {
    expect(manifest.name.length).toBeGreaterThan(0);
    // `short_name` is what fits under a home-screen icon; 12 chars is the
    // conventional ceiling before truncation.
    expect(manifest.short_name.length).toBeLessThanOrEqual(12);
    expect(manifest.start_url).toBe('/');
    expect(manifest.scope).toBe('/');
    expect(manifest.display).toBe('standalone');
    expect(manifest.icons.length).toBeGreaterThan(0);
    expect(manifest.background_color).toMatch(/^#[0-9a-f]{6}$/);
    expect(manifest.theme_color).toMatch(/^#[0-9a-f]{6}$/);
  });

  it('survives a JSON round trip unchanged (it is served as JSON)', () => {
    expect(JSON.parse(JSON.stringify(manifest))).toEqual(manifest);
  });

  it('opens the home surface, never a run (Rule 1)', () => {
    expect(manifest.start_url).not.toContain('/game');
    expect(manifest.start_url).not.toContain('/training');
    // No `shortcuts` key at all: a long-press shortcut into the arena is a
    // run the player did not choose to start.
    expect(manifest).not.toHaveProperty('shortcuts');
  });

  describe('icons', () => {
    it('declares the vector plus a raster ladder in both purposes', () => {
      const sources = PWA_ICONS.map((icon) => icon.src);
      expect(sources).toEqual([
        '/icon.svg',
        '/brand/icon-192.png',
        '/brand/icon-512.png',
        '/brand/icon-maskable-192.png',
        '/brand/icon-maskable-512.png',
      ]);
    });

    it('every referenced icon is backed by a committed file on disk', () => {
      // `/icon.svg` is served verbatim from src/app/icon.svg; the rasters are
      // static files under public/. If any is renamed, the manifest points at
      // a 404 and this fails.
      expect(existsSync(join(ROOT, 'src', 'app', 'icon.svg'))).toBe(true);
      for (const icon of PWA_ICONS.filter((i) => i.src.startsWith('/brand/'))) {
        expect(existsSync(join(ROOT, 'public', icon.src.slice(1)))).toBe(true);
      }
    });

    it('declares a vector icon for any size, which is the installability floor', () => {
      const svg = PWA_ICONS.find((icon) => icon.type === 'image/svg+xml');
      expect(svg).toBeDefined();
      expect(svg?.sizes).toBe('any');
    });

    it('every icon declares src, sizes and type', () => {
      for (const icon of PWA_ICONS) {
        expect(icon.src.startsWith('/')).toBe(true);
        expect(icon.sizes.length).toBeGreaterThan(0);
        expect(icon.type).toMatch(/^image\//);
      }
    });

    it('offers a maskable icon at both raster sizes, so no launcher letterboxes it', () => {
      const maskable = PWA_ICONS.filter((icon) => icon.purpose === 'maskable');
      expect(maskable.map((icon) => icon.sizes).sort()).toEqual(['192x192', '512x512']);
    });

    it('the declared sizes are the pixels the files actually contain', () => {
      // The rasters are generated by scripts/build-brand-assets.mjs. Reading
      // the PNG header keeps the manifest honest about what it is advertising
      // rather than trusting the filename.
      for (const icon of PWA_ICONS.filter((i) => i.type === 'image/png')) {
        const png = readFileSync(join(ROOT, 'public', icon.src.slice(1)));
        // IHDR width/height are big-endian uint32 at byte 16 and 20.
        const width = png.readUInt32BE(16);
        const height = png.readUInt32BE(20);
        expect(`${width}x${height}`).toBe(icon.sizes);
      }
    });

    it('ships the apple touch icon the App Router link tag points at', () => {
      // iOS reads the link tag, not the manifest, so this asset has no
      // manifest entry to keep it honest — hence a direct check.
      const apple = join(ROOT, 'src', 'app', 'apple-icon.png');
      expect(existsSync(apple)).toBe(true);
      const png = readFileSync(apple);
      expect(png.readUInt32BE(16)).toBe(APPLE_ICON_SIZE.width);
      expect(png.readUInt32BE(20)).toBe(APPLE_ICON_SIZE.height);
    });

    it('ships a favicon, which the repo previously had no file for at all', () => {
      expect(existsSync(join(ROOT, 'src', 'app', 'favicon.ico'))).toBe(true);
    });
  });

  it('tints the same as the browser tab (layout viewport.themeColor)', () => {
    const layout = readFileSync(join(ROOT, 'src', 'app', 'layout.tsx'), 'utf8');
    expect(layout).toContain(`themeColor: '${PWA_THEME_COLOR}'`);
    expect(PWA_BACKGROUND_COLOR).toBe('#06090d');
  });

  it('says nothing commercial — Rule 7 sweeps the home screen too', () => {
    expect(sweepMessage(manifestProse(manifest))).toEqual([]);
  });

  it('does not reuse SITE_DESCRIPTION, which the Rule 7 lint refuses here', () => {
    // "Every run ends with a deal" is right on a landing page and unreadable
    // on a home screen. The divergence is deliberate; this pins it so nobody
    // "fixes" the duplication by pointing the manifest back at the site copy.
    expect(manifest.description).not.toBe(SITE_DESCRIPTION);
    expect(sweepMessage({ site: SITE_DESCRIPTION }).length).toBeGreaterThan(0);
  });

  it('says nothing that guilts or implies decay — Rule 5', () => {
    expect(sweepForLoss(manifestProse(manifest))).toEqual([]);
  });
});
