#!/usr/bin/env node
/**
 * gear-economy.mjs — the Gear System economy simulator.
 *
 * Authority: docs/game/GEAR_SYSTEM_DESIGN.md §3. Every table in that section is
 * GENERATED by this script; if the two disagree, this file is right and the doc
 * is stale.
 *
 * DETERMINISM IS A HARD REQUIREMENT. There is no Math.random, no Date.now, no
 * clock, no I/O, and no floating-point accumulation that depends on iteration
 * order. Two runs on two machines produce byte-identical output, which is what
 * makes "the doc's tables are generated" a checkable claim rather than a habit.
 * The one seeded generator (mulberry32) exists for the OPTIONAL --jitter mode
 * and is unused by every table the doc cites.
 *
 * WHAT IT MODELS, AND WHAT IT DELIBERATELY DOES NOT.
 *
 * Models: the DNA faucet (per-dynasty food value, Energy commitment curve, lean
 * runs, Daily Take, Signal bonus), the DNA sink (gear levels under the 1.12
 * curve, then breeding under migration 047's 1.25 curve), the Scale faucet (six
 * lanes with their per-period caps), the Scale sink (rank promotion), the rank
 * ceiling that binds levels, the Ascendance multiplier, and the population
 * median that drives the Slipstream.
 *
 * Does NOT model: crash/bank variance, skill improvement over time, clan battle
 * outcomes beyond a fixed win rate, seasonal Standard Issue (a separate flag),
 * or churn. Each is a deliberate omission that makes the output a CEILING on
 * the gap between cohorts rather than an expectation — the conservative
 * direction for a fairness argument.
 *
 * Usage:
 *   node scripts/sim/gear-economy.mjs                 # base run, 24 months
 *   node scripts/sim/gear-economy.mjs --markdown      # doc-ready tables
 *   node scripts/sim/gear-economy.mjs --d2            # grinder-dial sensitivity
 *   node scripts/sim/gear-economy.mjs --d4            # gear-ceiling sensitivity
 *   node scripts/sim/gear-economy.mjs --slipstream    # catch-up sensitivity
 *   node scripts/sim/gear-economy.mjs --all --markdown
 *   node scripts/sim/gear-economy.mjs --validate      # assert the doc's figures
 */

// ===========================================================================
// 1. CONFIGURATION — every [H] number in the design document
// ===========================================================================

const CONFIG = {
  rigs: 7,

  // §3.3 — the DNA level curve. Level n costs round(60 * 1.12^(n-1)).
  levelBaseCost: 60,
  levelGrowth: 1.12,
  maxLevel: 60,
  levelPp: 0.2, // percentage points of Yield per level

  // §3.4 — the Scale rank ladder. Index r-1 = cost to REACH rank r.
  rankStepCost: [0, 1, 2, 4, 7, 11],
  rankBasePp: [0, 1, 2, 3, 4, 5],
  maxRank: 6,
  levelsPerRank: 10,

  // §3.6 — the effort lanes, in centiscales (1 Scale = 100).
  lanes: {
    signalPerDay: 10,
    takePerDay: 4,
    huntPerCycle: 25,
    victoryPerCycle: 10,
    victoryMonthlyCap: 70, // §5.3 A5 — win-trading defence
    ascensionBands: [0, 60, 100, 150],
    oneTimeLadderRung: 100,
  },
  cyclesPerMonth: 7,
  daysPerMonth: 30,
  months: 24,

  // Economy, from src/shared/config/game.ts
  foodBaseDna: 10,
  energyCap: 6,
  energyRecoveryPerDay: 24,
  commitmentMultiplier: 10.0, // 6-Energy commitment, 100_000 bps
  leanHarvestFactor: 0.25,
  dailyTakeBase: 100,
  dailyTakeMaxTier: 3.0,
  signalFirstCompletionBonus: 150,

  // Ascendance, from src/shared/game/ascendance.ts + migration 047
  ascendanceStartGen: 4,
  ascendanceFactor: 1.02,
  breedCostGrowth: 1.25,

  // §3.8 — the Slipstream
  slipstream: {
    mode: 'strong', // off | mild | strong
    mildRate: 1.5,
    strongRate: 2.0,
    entryPercentile: 0.5,
    exitPercentile: 0.6,
  },

  // Sensitivity dials, overridden by the --d2 / --d4 modes
  d2LaneScale: 1.0, // scales the OPTIONAL lanes only
  d4PpScale: 1.0, // scales all gear power
};

// Population weights for the median that drives the Slipstream. Deliberately
// pessimistic about how many players are diligent: a median dragged low by
// casual players makes the catch-up ramp fire for FEWER newcomers, so any
// fairness result the sim reports is a floor.
const POPULATION_WEIGHTS = {
  login_only: 0.4,
  casual: 0.3,
  full_lane: 0.2,
  max_grinder: 0.09,
  bot: 0.01,
};

// ===========================================================================
// 2. COHORTS
// ===========================================================================

/**
 * `foodsPerBank` is the skill dial and is the ONLY place skill enters. It is
 * set from the observed shape of real play, not from an ambition: the design
 * document's fairness inequality is measured against food count, so a sim that
 * gave every cohort the same skill would flatter the design by construction.
 */
const COHORTS = [
  {
    key: 'login_only',
    label: 'Login-only (daily ritual, nothing else)',
    startMonth: 1,
    activeDays: 30,
    signal: true,
    take: true,
    huntCycles: 0,
    victoryCycles: 0,
    ascensionBand: 0,
    ladderRungsTotal: 0,
    sessionsPerDay: 1,
    runsPerDay: 1,
    foodsPerBank: 24,
  },
  {
    key: 'casual',
    label: 'Casual (4 days/week, some lanes)',
    startMonth: 1,
    activeDays: 17,
    signal: true,
    take: true,
    huntCycles: 3,
    victoryCycles: 1,
    ascensionBand: 1,
    ladderRungsTotal: 2,
    sessionsPerDay: 1,
    runsPerDay: 2,
    foodsPerBank: 28,
  },
  {
    key: 'full_lane',
    label: 'Full-lane daily (finishes everything)',
    startMonth: 1,
    activeDays: 30,
    signal: true,
    take: true,
    huntCycles: 7,
    victoryCycles: 7,
    ascensionBand: 3,
    ladderRungsTotal: 6,
    sessionsPerDay: 3,
    runsPerDay: 4,
    foodsPerBank: 38,
  },
  {
    key: 'max_grinder',
    label: 'Maximum grinder (every lane + every trial, all day)',
    startMonth: 1,
    activeDays: 30,
    signal: true,
    take: true,
    huntCycles: 7,
    victoryCycles: 7,
    ascensionBand: 3,
    ladderRungsTotal: 11,
    sessionsPerDay: 4,
    runsPerDay: 12,
    foodsPerBank: 44,
  },
  {
    key: 'bot',
    label: 'Perfect bot (400 runs/day, never sleeps)',
    startMonth: 1,
    activeDays: 30,
    signal: true,
    take: true,
    huntCycles: 7,
    victoryCycles: 7,
    ascensionBand: 3,
    ladderRungsTotal: 11,
    sessionsPerDay: 4,
    runsPerDay: 400,
    foodsPerBank: 24,
  },
];

const LATE_JOINER = {
  key: 'late_joiner',
  label: 'Late joiner (starts month 13, plays full-lane)',
  startMonth: 13,
  activeDays: 30,
  signal: true,
  take: true,
  huntCycles: 7,
  victoryCycles: 7,
  ascensionBand: 3,
  ladderRungsTotal: 6,
  sessionsPerDay: 3,
  runsPerDay: 4,
  foodsPerBank: 38,
};

// ===========================================================================
// 3. PRIMITIVES — each mirrors a shipped code path, cited
// ===========================================================================

/** CYBER's shipped food value: src/shared/game/rulesets.ts:397 and :240. */
function cyberFoodDna(n) {
  const tier = Math.min(4, Math.floor(n / 5));
  return Math.round(CONFIG.foodBaseDna * (1 + 0.5 * tier));
}

/** Base Yield of a banked run of `foods` foods, CYBER. Integer, like the fold. */
function baseYield(foods) {
  let total = 0;
  for (let n = 1; n <= foods; n++) total += cyberFoodDna(n);
  return total;
}

/** §3.3 — the cost of buying level `n` on one rig. */
function levelCost(n) {
  return Math.round(CONFIG.levelBaseCost * Math.pow(CONFIG.levelGrowth, n - 1));
}

/** Percentage points a single rig contributes at (rank, level). */
function rigPp(rank, level) {
  const base = CONFIG.rankBasePp[rank - 1] + CONFIG.levelPp * level;
  return base * CONFIG.d4PpScale;
}

/** Migration 047: ceil((200 + floor((g1+g2)/2)*100) * 1.25^(childGen-3)). */
function breedCost(childGen) {
  const base = 200 + Math.floor((childGen - 1 + 1) / 2) * 100;
  const steps = Math.max(0, childGen - 3);
  return Math.ceil(base * Math.pow(CONFIG.breedCostGrowth, steps));
}

/** src/shared/game/ascendance.ts — v2, Gen4+ compounds 1.02. */
function ascendanceMultiplier(generation) {
  const steps = Math.max(0, generation - (CONFIG.ascendanceStartGen - 1));
  return Math.pow(CONFIG.ascendanceFactor, steps);
}

/** Seeded PRNG, used only by the optional --jitter mode. */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ===========================================================================
// 4. THE PLAYER STATE MACHINE
// ===========================================================================

function newPlayer(cohort) {
  return {
    cohort,
    // 7 rigs, each {rank, level}. Rank I and level 1 are granted with the rig.
    rigs: Array.from({ length: CONFIG.rigs }, () => ({ rank: 1, level: 1 })),
    centiscales: 0,
    dna: 0,
    generation: 1,
    lifetimeDnaEarned: 0,
    lifetimeDnaSpentGear: 0,
    lifetimeDnaSpentBreeding: 0,
    lifetimeCentiscales: 0,
    ladderRungsClaimed: 0,
  };
}

function gearPp(p) {
  return p.rigs.reduce((sum, r) => sum + rigPp(r.rank, r.level), 0);
}

function gearMultiplier(p) {
  return 1 + gearPp(p) / 100;
}

function ownedPowerBps(p) {
  return Math.round(gearPp(p) * 100);
}

/**
 * The DNA a cohort credits in one month, at its CURRENT multipliers.
 *
 * Compounding is real and deliberate: gear multiplies Yield, Yield drives
 * credited DNA, credited DNA buys gear. The sim resolves this month-by-month
 * rather than continuously, which understates the rich-get-richer effect
 * slightly — again the conservative direction.
 */
function monthlyDna(p) {
  const c = p.cohort;
  const yieldPerBank = baseYield(c.foodsPerBank);
  const mult = gearMultiplier(p) * ascendanceMultiplier(p.generation);

  const energyPerDay = Math.min(
    CONFIG.energyRecoveryPerDay,
    c.sessionsPerDay * CONFIG.energyCap
  );
  const chargedRuns = Math.floor(energyPerDay / CONFIG.energyCap);
  const leanRuns = Math.max(0, c.runsPerDay - chargedRuns);

  const chargedDna = chargedRuns * yieldPerBank * CONFIG.commitmentMultiplier;
  const leanDna = leanRuns * yieldPerBank * CONFIG.leanHarvestFactor;
  const take = c.take ? CONFIG.dailyTakeBase * CONFIG.dailyTakeMaxTier : 0;
  const signal = c.signal ? CONFIG.signalFirstCompletionBonus : 0;

  const perDay = (chargedDna + leanDna) * mult + take + signal;
  return Math.round(perDay * c.activeDays);
}

/** The centiscales a cohort earns in one month, every lane capped. */
function monthlyCentiscales(p, slipstreamRate) {
  const c = p.cohort;
  const L = CONFIG.lanes;
  const k = CONFIG.d2LaneScale;

  // Floor lanes: the daily ritual. NOT scaled by the D2 dial — the dial moves
  // the reward for extra effort, not the reward for showing up.
  const floorLanes = (c.signal ? L.signalPerDay : 0) * c.activeDays
    + (c.take ? L.takePerDay : 0) * c.activeDays;

  // Optional lanes: what "finishing all the lanes" actually pays.
  const hunt = c.huntCycles * L.huntPerCycle;
  const victory = Math.min(c.victoryCycles * L.victoryPerCycle, L.victoryMonthlyCap);
  const ascension = L.ascensionBands[c.ascensionBand];
  const optionalLanes = (hunt + victory + ascension) * k;

  // One-time skill lane: ladder rungs and Mastery trials, front-loaded over the
  // first three months. Not part of the sustained cadence.
  let oneTime = 0;
  if (p.monthIndex <= 3 && p.ladderRungsClaimed < c.ladderRungsTotal) {
    const perMonth = Math.ceil(c.ladderRungsTotal / 3);
    const claim = Math.min(perMonth, c.ladderRungsTotal - p.ladderRungsClaimed);
    oneTime = claim * L.oneTimeLadderRung;
    p.ladderRungsClaimed += claim;
  }

  return Math.round((floorLanes + optionalLanes + oneTime) * slipstreamRate);
}

/**
 * Spend Scales greedily on the cheapest available rank promotion.
 *
 * Greedy is provably optimal here because all rigs are identical and marginal
 * power per Scale falls monotonically (3.0 -> 1.5 -> 0.75 -> 0.43 -> 0.27 pp),
 * so the cheapest promotion is always the most valuable one. Uniform ranks fall
 * out of that rather than being assumed.
 */
function spendScales(p) {
  for (;;) {
    let best = -1;
    let bestCost = Infinity;
    for (let i = 0; i < p.rigs.length; i++) {
      const r = p.rigs[i];
      if (r.rank >= CONFIG.maxRank) continue;
      const cost = CONFIG.rankStepCost[r.rank] * 100;
      if (cost < bestCost) {
        bestCost = cost;
        best = i;
      }
    }
    if (best < 0 || bestCost > p.centiscales) break;
    p.centiscales -= bestCost;
    p.rigs[best].rank += 1;
  }
}

/** Spend DNA: cheapest available level first, then breeding with the surplus. */
function spendDna(p) {
  for (;;) {
    let best = -1;
    let bestCost = Infinity;
    for (let i = 0; i < p.rigs.length; i++) {
      const r = p.rigs[i];
      const ceiling = Math.min(CONFIG.maxLevel, r.rank * CONFIG.levelsPerRank);
      if (r.level >= ceiling) continue;
      const cost = levelCost(r.level + 1);
      if (cost < bestCost) {
        bestCost = cost;
        best = i;
      }
    }
    if (best < 0 || bestCost > p.dna) break;
    p.dna -= bestCost;
    p.lifetimeDnaSpentGear += bestCost;
    p.rigs[best].level += 1;
  }

  // Surplus goes to Ascendance. Gear first because it compounds into the
  // faucet; breeding second because it is the bottomless sink behind it.
  for (;;) {
    const cost = breedCost(p.generation + 1);
    if (cost > p.dna) break;
    p.dna -= cost;
    p.lifetimeDnaSpentBreeding += cost;
    p.generation += 1;
  }
}

// ===========================================================================
// 5. THE SIMULATION
// ===========================================================================

function weightedMedianPower(players) {
  const entries = players
    .filter((p) => POPULATION_WEIGHTS[p.cohort.key] !== undefined)
    .map((p) => ({ power: ownedPowerBps(p), w: POPULATION_WEIGHTS[p.cohort.key] }))
    .sort((a, b) => a.power - b.power);
  const total = entries.reduce((s, e) => s + e.w, 0);
  let acc = 0;
  for (const e of entries) {
    acc += e.w;
    if (acc >= total * CONFIG.slipstream.entryPercentile) return e.power;
  }
  return entries.length ? entries[entries.length - 1].power : 0;
}

function percentilePower(players, q) {
  const entries = players
    .filter((p) => POPULATION_WEIGHTS[p.cohort.key] !== undefined)
    .map((p) => ({ power: ownedPowerBps(p), w: POPULATION_WEIGHTS[p.cohort.key] }))
    .sort((a, b) => a.power - b.power);
  const total = entries.reduce((s, e) => s + e.w, 0);
  let acc = 0;
  for (const e of entries) {
    acc += e.w;
    if (acc >= total * q) return e.power;
  }
  return entries.length ? entries[entries.length - 1].power : 0;
}

function slipstreamRate(p, median, p60) {
  const mode = CONFIG.slipstream.mode;
  if (mode === 'off') return 1;
  const rate = mode === 'mild' ? CONFIG.slipstream.mildRate : CONFIG.slipstream.strongRate;
  const power = ownedPowerBps(p);
  if (power >= p60) return 1;
  if (power >= median) return 1;
  return rate;
}

function simulate({ includeLateJoiner = true } = {}) {
  const defs = includeLateJoiner ? [...COHORTS, LATE_JOINER] : [...COHORTS];
  const players = defs.map(newPlayer);
  const history = [];

  for (let month = 1; month <= CONFIG.months; month++) {
    const active = players.filter((p) => month >= p.cohort.startMonth);
    const median = weightedMedianPower(players.filter((p) => month >= p.cohort.startMonth));
    const p60 = percentilePower(
      players.filter((p) => month >= p.cohort.startMonth),
      CONFIG.slipstream.exitPercentile
    );

    const snapshot = { month, rows: [] };

    for (const p of active) {
      p.monthIndex = month - p.cohort.startMonth + 1;

      const dnaEarned = monthlyDna(p);
      p.dna += dnaEarned;
      p.lifetimeDnaEarned += dnaEarned;

      const rate = slipstreamRate(p, median, p60);
      const cs = monthlyCentiscales(p, rate);
      p.centiscales += cs;
      p.lifetimeCentiscales += cs;

      spendScales(p);
      spendDna(p);

      snapshot.rows.push({
        key: p.cohort.key,
        label: p.cohort.label,
        dnaEarned,
        dnaSpentGear: p.lifetimeDnaSpentGear,
        dnaSpentBreeding: p.lifetimeDnaSpentBreeding,
        dnaBanked: p.dna,
        scalesEarnedMonth: cs / 100,
        scalesLifetime: p.lifetimeCentiscales / 100,
        slipstreamRate: rate,
        ranks: p.rigs.map((r) => r.rank).join(''),
        minRank: Math.min(...p.rigs.map((r) => r.rank)),
        maxRank: Math.max(...p.rigs.map((r) => r.rank)),
        minLevel: Math.min(...p.rigs.map((r) => r.level)),
        maxLevel: Math.max(...p.rigs.map((r) => r.level)),
        kitPp: gearPp(p),
        gearMult: gearMultiplier(p),
        generation: p.generation,
        ascMult: ascendanceMultiplier(p.generation),
        totalMult: gearMultiplier(p) * ascendanceMultiplier(p.generation),
        runYield: Math.round(
          baseYield(p.cohort.foodsPerBank) * gearMultiplier(p) * ascendanceMultiplier(p.generation)
        ),
      });
    }
    history.push(snapshot);
  }
  return { players, history };
}

// ===========================================================================
// 6. REPORTING
// ===========================================================================

const fmt = (n, d = 0) => Number(n).toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
const row = (cells) => `| ${cells.join(' | ')} |`;
const sep = (n) => `|${' --- |'.repeat(n)}`;

function at(history, month, key) {
  return history[month - 1].rows.find((r) => r.key === key);
}

function tableCohortTrajectory(history, months = [1, 3, 6, 12, 18, 24]) {
  const out = [];
  out.push('#### Cohort trajectory — kit power and Yield multiplier');
  out.push('');
  out.push(row(['Month', ...COHORTS.map((c) => c.key)]));
  out.push(sep(COHORTS.length + 1));
  for (const m of months) {
    out.push(
      row([
        `**${m}**`,
        ...COHORTS.map((c) => {
          const r = at(history, m, c.key);
          return `${fmt(r.kitPp, 0)} pp · ×${fmt(r.gearMult, 2)}`;
        }),
      ])
    );
  }
  return out.join('\n');
}

function tableScales(history, months = [1, 3, 6, 12, 18, 24]) {
  const out = [];
  out.push('#### Scales earned (lifetime, monthly ceiling enforced)');
  out.push('');
  out.push(row(['Month', ...COHORTS.map((c) => c.key)]));
  out.push(sep(COHORTS.length + 1));
  for (const m of months) {
    out.push(
      row([`**${m}**`, ...COHORTS.map((c) => fmt(at(history, m, c.key).scalesLifetime, 1))])
    );
  }
  return out.join('\n');
}

function tableDna(history, months = [1, 6, 12, 24]) {
  const out = [];
  out.push('#### DNA — earned this month / spent on gear / spent on breeding (lifetime)');
  out.push('');
  out.push(
    row(['Cohort', ...months.map((m) => `M${m} earned`), 'Gear (life)', 'Breeding (life)', 'Gen @24'])
  );
  out.push(sep(months.length + 4));
  for (const c of COHORTS) {
    const last = at(history, 24, c.key);
    out.push(
      row([
        c.key,
        ...months.map((m) => fmt(at(history, m, c.key).dnaEarned)),
        fmt(last.dnaSpentGear),
        fmt(last.dnaSpentBreeding),
        String(last.generation),
      ])
    );
  }
  return out.join('\n');
}

function tableGaps(history) {
  const out = [];
  out.push('#### The gaps that matter');
  out.push('');
  out.push(
    row([
      'Month',
      'login-only gear',
      'full-lane gear',
      '**GEAR gap**',
      'bot gear',
      '**bot gear vs full-lane**',
      'bot DNA ÷ login-only DNA',
      'login-only total ×',
      'bot total ×',
      '**TOTAL gap (gear × Ascendance)**',
    ])
  );
  out.push(sep(10));
  for (const m of [6, 12, 18, 24]) {
    const lo = at(history, m, 'login_only');
    const fl = at(history, m, 'full_lane');
    const bot = at(history, m, 'bot');
    out.push(
      row([
        `**${m}**`,
        `×${fmt(lo.gearMult, 3)}`,
        `×${fmt(fl.gearMult, 3)}`,
        `**+${fmt((fl.gearMult / lo.gearMult - 1) * 100, 1)}%**`,
        `×${fmt(bot.gearMult, 3)}`,
        `**+${fmt((bot.gearMult / fl.gearMult - 1) * 100, 1)}%**`,
        `${fmt(bot.dnaEarned / lo.dnaEarned, 1)}×`,
        `×${fmt(lo.totalMult, 2)}`,
        `×${fmt(bot.totalMult, 2)}`,
        `**+${fmt((bot.totalMult / lo.totalMult - 1) * 100, 1)}%**`,
      ])
    );
  }
  return out.join('\n');
}

function levelCostTable() {
  const out = [];
  out.push('#### Level costs (generated)');
  out.push('');
  out.push(row(['Level', 'Cost of that level', 'Cumulative, one rig', 'Cumulative, all 7']));
  out.push(sep(4));
  let cum = 0;
  const marks = [1, 10, 20, 30, 40, 50, 60];
  for (let n = 1; n <= CONFIG.maxLevel; n++) {
    cum += levelCost(n);
    if (marks.includes(n)) {
      out.push(row([String(n), fmt(levelCost(n)), fmt(cum), fmt(cum * CONFIG.rigs)]));
    }
  }
  return out.join('\n');
}

function rankTable() {
  const out = [];
  out.push('#### Rank ladder (generated)');
  out.push('');
  out.push(row(['Rank', 'Scales for this promotion', 'Cumulative', 'Level cap', 'Rank base', 'Rig total at cap']));
  out.push(sep(6));
  let cum = 0;
  for (let R = 1; R <= CONFIG.maxRank; R++) {
    cum += CONFIG.rankStepCost[R - 1];
    const cap = R * CONFIG.levelsPerRank;
    out.push(
      row([
        ['I', 'II', 'III', 'IV', 'V', 'VI'][R - 1],
        R === 1 ? '— (granted)' : String(CONFIG.rankStepCost[R - 1]),
        String(cum),
        String(cap),
        `+${fmt(CONFIG.rankBasePp[R - 1], 1)} pp`,
        `**${fmt(rigPp(R, cap), 1)} pp**`,
      ])
    );
  }
  const full = CONFIG.rigs * rigPp(CONFIG.maxRank, CONFIG.maxLevel);
  out.push('');
  out.push(
    `Complete kit: **${fmt(full, 0)} pp**, **G = ×${fmt(1 + full / 100, 2)}**, costing **${
      CONFIG.rigs * 25
    } Scales** and **${fmt(
      CONFIG.rigs * Array.from({ length: 60 }, (_, i) => levelCost(i + 1)).reduce((a, b) => a + b, 0)
    )} DNA**.`
  );
  return out.join('\n');
}

// ===========================================================================
// 7. SENSITIVITY MODES
// ===========================================================================

function withConfig(overrides, fn) {
  const saved = {};
  for (const k of Object.keys(overrides)) {
    saved[k] = CONFIG[k];
    CONFIG[k] = overrides[k];
  }
  try {
    return fn();
  } finally {
    for (const k of Object.keys(saved)) CONFIG[k] = saved[k];
  }
}

/** D2 — the grinder dial. Target ratio of full-lane to login-only cadence. */
function d2Sensitivity() {
  const floorCs = (CONFIG.lanes.signalPerDay + CONFIG.lanes.takePerDay) * CONFIG.daysPerMonth;
  const optionalCs =
    7 * CONFIG.lanes.huntPerCycle + CONFIG.lanes.victoryMonthlyCap + CONFIG.lanes.ascensionBands[3];

  const out = [];
  out.push('#### D2 · the grinder dial');
  out.push('');
  out.push(
    row(['Target ratio', 'Lane scale k', 'full-lane Scales/mo', 'Y1 gear gap', 'Y2 gear gap', 'full-lane kit @24mo', 'months to full kit'])
  );
  out.push(sep(7));

  for (const target of [1.5, 1.94, 3.0]) {
    const k = ((target - 1) * floorCs) / optionalCs;
    const res = withConfig({ d2LaneScale: k }, () => simulate({ includeLateJoiner: false }));
    const h = res.history;
    const y1lo = at(h, 12, 'login_only').gearMult;
    const y1fl = at(h, 12, 'full_lane').gearMult;
    const y2lo = at(h, 24, 'login_only').gearMult;
    const y2fl = at(h, 24, 'full_lane').gearMult;
    const flMonthly = (floorCs + optionalCs * k) / 100;
    let monthsToFull = '—';
    for (let m = 1; m <= CONFIG.months; m++) {
      if (at(h, m, 'full_lane').kitPp >= CONFIG.rigs * rigPp(6, 60) - 0.01) {
        monthsToFull = String(m);
        break;
      }
    }
    out.push(
      row([
        `**${fmt(target, 2)}×**${target === 1.94 ? ' *(doc)*' : ''}`,
        fmt(k, 3),
        fmt(flMonthly, 1),
        `**+${fmt((y1fl / y1lo - 1) * 100, 1)}%**`,
        `**+${fmt((y2fl / y2lo - 1) * 100, 1)}%**`,
        `${fmt(at(h, 24, 'full_lane').kitPp, 0)} pp`,
        monthsToFull,
      ])
    );
  }
  return out.join('\n');
}

/** D4 — the gear ceiling, against the run's own skill lever. */
function d4Sensitivity() {
  const fullPp = CONFIG.rigs * (CONFIG.rankBasePp[5] + CONFIG.levelPp * 60);
  const out = [];
  out.push('#### D4 · the gear ceiling, against piloting');
  out.push('');
  out.push(
    row([
      'Ceiling',
      'pp scale',
      'Full kit',
      'Skill lever 24→48 foods',
      'Gear overtakes piloting?',
      'Food gap that erases full gear',
      'Y1 gear gap',
    ])
  );
  out.push(sep(7));

  const y24 = baseYield(24);
  for (const target of [1.8, 2.19, 2.6]) {
    const scale = ((target - 1) * 100) / fullPp;
    const res = withConfig({ d4PpScale: scale }, () => simulate({ includeLateJoiner: false }));
    const h = res.history;
    const skillLever = baseYield(48) / y24;
    // The food count at which a bare pilot matches a 24-food run wearing full gear.
    let breakEven = null;
    for (let f = 24; f <= 200; f++) {
      if (baseYield(f) >= y24 * target) {
        breakEven = f;
        break;
      }
    }
    const y1lo = at(h, 12, 'login_only').gearMult;
    const y1fl = at(h, 12, 'full_lane').gearMult;
    out.push(
      row([
        `**×${fmt(target, 2)}**${target === 2.19 ? ' *(doc)*' : ''}`,
        fmt(scale, 3),
        `${fmt(fullPp * scale, 0)} pp`,
        `×${fmt(skillLever, 2)}`,
        target > skillLever ? '**YES — gear wins**' : 'no',
        breakEven ? `24 → ${breakEven} foods (+${breakEven - 24})` : '>200 foods',
        `+${fmt((y1fl / y1lo - 1) * 100, 1)}%`,
      ])
    );
  }
  return out.join('\n');
}

/** Slipstream — a month-13 joiner's distance from the field at month 18. */
function slipstreamSensitivity() {
  const out = [];
  out.push('#### Slipstream · a month-13 arrival, measured at month 18');
  out.push('');
  out.push(
    row(['Mode', 'Rate', 'Joiner kit @18', 'Median @18', 'Veteran (full-lane) @18', 'Joiner vs median', 'Joiner vs veteran', 'Months to reach median'])
  );
  out.push(sep(8));

  for (const mode of ['off', 'mild', 'strong']) {
    const res = withConfig({ slipstream: { ...CONFIG.slipstream, mode } }, () => simulate());
    const h = res.history;
    const j18 = at(h, 18, 'late_joiner');
    const v18 = at(h, 18, 'full_lane');
    const medianRow = h[17].rows.filter((r) => POPULATION_WEIGHTS[r.key] !== undefined);
    const sorted = medianRow
      .map((r) => ({ pp: r.kitPp, w: POPULATION_WEIGHTS[r.key] }))
      .sort((a, b) => a.pp - b.pp);
    let acc = 0;
    const totalW = sorted.reduce((s, e) => s + e.w, 0);
    let medianPp = sorted[sorted.length - 1].pp;
    for (const e of sorted) {
      acc += e.w;
      if (acc >= totalW * 0.5) {
        medianPp = e.pp;
        break;
      }
    }
    let monthsToMedian = '—';
    for (let m = 13; m <= CONFIG.months; m++) {
      const jr = at(h, m, 'late_joiner');
      const rowsM = h[m - 1].rows.filter((r) => POPULATION_WEIGHTS[r.key] !== undefined);
      const s2 = rowsM.map((r) => ({ pp: r.kitPp, w: POPULATION_WEIGHTS[r.key] })).sort((a, b) => a.pp - b.pp);
      let a2 = 0;
      const t2 = s2.reduce((s, e) => s + e.w, 0);
      let med2 = s2[s2.length - 1].pp;
      for (const e of s2) {
        a2 += e.w;
        if (a2 >= t2 * 0.5) {
          med2 = e.pp;
          break;
        }
      }
      if (jr.kitPp >= med2) {
        monthsToMedian = String(m - 12);
        break;
      }
    }
    out.push(
      row([
        `**${mode}**${mode === 'strong' ? ' *(doc)*' : ''}`,
        mode === 'off' ? '×1.0' : mode === 'mild' ? '×1.5' : '×2.0',
        `${fmt(j18.kitPp, 0)} pp · ×${fmt(j18.gearMult, 2)}`,
        `${fmt(medianPp, 0)} pp`,
        `${fmt(v18.kitPp, 0)} pp · ×${fmt(v18.gearMult, 2)}`,
        `${fmt((j18.gearMult / (1 + medianPp / 100) - 1) * 100, 1)}%`,
        `${fmt((j18.gearMult / v18.gearMult - 1) * 100, 1)}%`,
        monthsToMedian,
      ])
    );
  }
  return out.join('\n');
}

// ===========================================================================
// 8. VALIDATION — the design document's claims, asserted
// ===========================================================================

function validate() {
  const checks = [];
  const ok = (name, actual, expected, tol = 0) => {
    const pass = tol === 0 ? actual === expected : Math.abs(actual - expected) <= tol;
    checks.push({ name, actual, expected, pass });
  };

  ok('§1.3 base Yield @24 foods (CYBER)', baseYield(24), 490);
  ok('§1.3 base Yield @48 foods (CYBER)', baseYield(48), 1210);
  ok('§1.3 skill lever 24→48', Number((baseYield(48) / baseYield(24)).toFixed(2)), 2.47, 0.005);

  let cum = 0;
  for (let n = 1; n <= 10; n++) cum += levelCost(n);
  ok('§3.3 cumulative to level 10, one rig', cum, 1052);
  ok('§3.3 first full kit at Rank I (7 rigs, L10)', cum * 7, 7364);
  for (let n = 11; n <= 60; n++) cum += levelCost(n);
  ok('§3.3 cumulative to level 60, one rig', cum, 448296);
  ok('§3.3 complete level-60 kit, all 7', cum * 7, 3138072);

  ok('§3.4 complete kit pp', CONFIG.rigs * rigPp(6, 60), 119, 0.001);
  ok('§3.4 complete kit multiplier', Number((1 + (CONFIG.rigs * rigPp(6, 60)) / 100).toFixed(2)), 2.19, 0.005);
  ok('§3.4 complete kit Scale cost', CONFIG.rigs * 25, 175);

  const floorCs = 30 * 10 + 30 * 4;
  const fullCs = floorCs + 7 * 25 + 70 + 150;
  ok('§3.6 floor cadence, Scales/month', floorCs / 100, 4.2, 0.001);
  ok('§3.6 full cadence, Scales/month', fullCs / 100, 8.15, 0.001);
  ok('§3.6 grinder ratio', Number((fullCs / floorCs).toFixed(2)), 1.94, 0.005);

  ok('§3.7 months to full kit, floor', Math.ceil(175 / (floorCs / 100)), 42);
  ok('§3.7 months to full kit, full-lane', Math.ceil(175 / (fullCs / 100)), 22);

  // The 12-month spread, from the discrete ladder rather than a fitted curve.
  const uniform = (scales) => {
    let rank = 1;
    for (let k = 1; k <= 6; k++) if (7 * [0, 1, 3, 7, 14, 25][k - 1] <= scales) rank = k;
    return { rank, pp: 7 * rigPp(rank, rank * 10) };
  };
  const f = uniform(50);
  const m = uniform(98);
  ok('§3.7 floor @12mo, uniform rank', f.rank, 4);
  ok('§3.7 floor @12mo, kit pp', f.pp, 77, 0.001);
  ok('§3.7 full @12mo, uniform rank', m.rank, 5);
  ok('§3.7 full @12mo, kit pp', m.pp, 98, 0.001);
  ok(
    '§3.7 12-month output ratio',
    Number(((1 + m.pp / 100) / (1 + f.pp / 100)).toFixed(3)),
    1.119,
    0.002
  );

  ok('§3.10 Ascendance @Gen22', Number(ascendanceMultiplier(22).toFixed(3)), 1.457, 0.001);
  ok('§3.10 base Yield @44 foods', baseYield(44), 1090);

  const width = Math.max(...checks.map((c) => c.name.length));
  const lines = checks.map(
    (c) =>
      `${c.pass ? 'PASS' : 'FAIL'}  ${c.name.padEnd(width)}  actual=${c.actual}  expected=${c.expected}`
  );
  const failed = checks.filter((c) => !c.pass).length;
  lines.push('');
  lines.push(`${checks.length - failed}/${checks.length} checks passed.`);
  return { text: lines.join('\n'), failed };
}

// ===========================================================================
// 9. MAIN
// ===========================================================================

const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);

if (has('--validate')) {
  const v = validate();
  console.log(v.text);
  process.exit(v.failed === 0 ? 0 : 1);
}

const all = has('--all');
const sections = [];

if (all || (!has('--d2') && !has('--d4') && !has('--slipstream'))) {
  const { history } = simulate();
  sections.push(levelCostTable());
  sections.push(rankTable());
  sections.push(tableCohortTrajectory(history));
  sections.push(tableScales(history));
  sections.push(tableDna(history));
  sections.push(tableGaps(history));
}
if (all || has('--d2')) sections.push(d2Sensitivity());
if (all || has('--d4')) sections.push(d4Sensitivity());
if (all || has('--slipstream')) sections.push(slipstreamSensitivity());

console.log(sections.join('\n\n'));
